### ISSUE TITLE
Dependobot: Feature scripts don't work right on it

### ISSUE THREAD

**Issue by davidrans** [iFixit/git-scripts#156]
@k0rvusk0r4x commented on [Wed Jun 26 2019](https://github.com/iFixit/ifixit/issues/29343)

## Problem

We can't use our feature scripts to deploy pulls from dependobot. Looks like it is not recognizing anything before the last /:

<details>
<summary>feature switch using name number with -n works:</summary>

```
Error: Invalid branch name: 'dependabot/npm_and_yarn/Tests/ImageDiff/underscore.string-3.3.5'


Git Feature Branch Helper

usage:
    list     feature list [-v]
    url      feature url [name-of-feature]
    start    feature start name-of-feature
    switch   feature switch (name-of-feature | -n number-of-feature)
[options]
    finish   feature finish [name-of-feature]
    finish-issue feature finish-issue issue-number
    merge    feature merge (name-of-feature | -n number-of-feature)
    pull     feature pull
    prune    feature prune <local | origin> <preview | clean>
    status   feature status
    stashes  feature stashes [-v]
    github-test feature github-test

arguments:
   name-of-feature: letters, numbers, and dashes

Look at the source to discover what each of these commands does.
```
</details>

<details>
<summary>feature pull (git pull works):</summary>

```
> git fetch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 2), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (5/5), done.
From github.com:iFixit/ifixit
 * [new branch]              guidepdf--migration-to-invalidate-pdfs -> origin/guidepdf--migration-to-invalidate-pdfs
Your branch underscore.string-3.3.5 hasn't been pushed, nothing to pull from
```
</details>

<details>
<summary>feature merge:</summary>

```
No pull request found for this branch.
Validating that this pull request has all the required labels
Traceback (most recent call last):
        6: from /usr/local/bin/feature:23:in `<main>'
        5: from /usr/local/bin/feature:23:in `load'
        4: from /usr/local/share/gems/gems/git-scripts-0.8.1/bin/feature:197:in `<top (required)>'
        3: from /usr/local/share/gems/gems/git-scripts-0.8.1/lib/plugins.rb:7:in `invoke'
        2: from /usr/local/share/gems/gems/git-scripts-0.8.1/lib/plugins.rb:7:in `each'
        1: from /usr/local/share/gems/gems/git-scripts-0.8.1/lib/plugins.rb:9:in `block in invoke'
/usr/local/share/gems/gems/git-scripts-0.8.1/plugins/check-labels.rb:31:in `before_merge': undefined method `number' for nil:NilClass (NoMethodError)
```
</details>

## Do This

Make this work right so we can deploy these pulls.

## Background

Found this while trying to deploy dependobot pulls that are ready.

CC: @iFixit/pms 

---

@addison-grant commented on [Thu Jun 27 2019](https://github.com/iFixit/ifixit/issues/29343#issuecomment-506488357)

Another example
![Screen Shot 2019-06-27 at 12 57 07](https://user-images.githubusercontent.com/10889879/60296513-1939f800-98db-11e9-8c9e-b851871fb324.png)

**Comment by addison-grant** [comment]
This should be fixed as of https://github.com/iFixit/git-scripts/pull/154! It looks like this was automatically migrated here. Reopen if you think my closing it was a mistake.
